/// <reference types="astro/client" />

/**
 * Types for values Astro cannot infer on its own.
 * `.astro/types.d.ts` (generated by `astro sync`) covers the rest.
 */

interface ImportMetaEnv {
  /**
   * Cloudflare Turnstile *site* key. Public by design — it is baked into the HTML
   * at build time, which is why it is a `PUBLIC_` variable and not a secret.
   * The matching secret key lives as a Worker secret; see docs/deploy-pipeline.md.
   */
  readonly PUBLIC_TURNSTILE_SITE_KEY?: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}

/** Global injected by Cloudflare's Turnstile script, when it is loaded. */
interface Window {
  turnstile?: {
    reset: (widget?: string | HTMLElement) => void;
    render: (container: string | HTMLElement, options: Record<string, unknown>) => string;
  };
}
